### ISSUE TITLE
似乎有内存溢出

### ISSUE THREAD

**Issue by SawyerEve** [suifengqjn/TBPlayer#5]
![5566](https://cloud.githubusercontent.com/assets/13621650/14137386/32906014-f69a-11e5-80dc-92e83b05e04f.png)
如图 播放器释放时 anonymous VM一直在增长

**Comment by suifengqjn** [comment]
模拟器会出现这种情况，真机不会

**Comment by SawyerEve** [comment]
好像是的 然后还有一个问题是 http://baobab.wdjcdn.com/14571455324031.mp4 您试一下用这个链接 好像没办法保存在沙盒
